name: Rust CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1 #  We can manually install the toolchain by running the command `rustup toolchain install stable --profile minimal`
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1 #  We can manually install the toolchain by running the command `rustup toolchain install stable --profile minimal`
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        registry: docker.pkg.github.com
        username: tonyng147
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: ./Dockerfile
        repository: 74th/try-github-container-registry/nginx
        tags: latest
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy source to Render server.
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
